### This Linear Algebra Course is provided by Jon Kronh [`(youtube.com)`](https://youtube.com/playlist?list=PLRDl2inPrWQW1QSWhBU0ki-jq_uElkh2a&si=enoqESi8RweoMRqV)

## 1 Tensors
**Description:** Machine Learning (ML) generalization of vectors and matrics to any number of dimensions. (สามารถสรุปผลเวกเตอร์และเมทริกซ์ไปยังมิติใดๆก็ได้)

| Dimensions | Mathematical Name | Description                         |
|------------|-------------------|-------------------------------------|
| $0$        | Scalar            | Magnitude only, มีเพียงขนาด (ไม่มีทิศทาง)                    |
| $1$        | Vector            | Array                               |
| $2$        | Matrix            | Flat table (e.g., square)           |
| $3$        | $3$-tensor        | 3D table (e.g., cube)               |
| $n$        | $n$-tensor        | Higher-dimensional |
---------------------------------------------------------------------------------------------------------------------------------------------------------------

## 1.1 Scalars
- No dimension
- Single number
- Denoted in lowercase, italics, e.g.: $\mathbf{x}$, ${x}$
- Should be typed, like all other tensors: e.g., int (integer), float

In [2]:
x_scalar = 25
print(type(x_scalar))

y_scalar = 3
print(type(y_scalar))

print(x_scalar+y_scalar)

<class 'int'>
<class 'int'>
28


## 1.1.1 Scalars in PyTorch

In [3]:
import torch

x_torch_scalar = torch.tensor(25)
print(type(x_torch_scalar))
print(x_torch_scalar.shape)

<class 'torch.Tensor'>
torch.Size([])


- **PyTorch are designed to be pythonic**, so it's easier to use and learn. TensorFlow is for infrastructure.

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## 1.2 Vectors
- One-dimension array of numbers
- Denoted in lowercase, italics, bold, e.g., $\mathbf{x}$, ${x}$, *x*
- Arranged in an order, element can be accessed by its index `(idx)`
    - Elements are scalar (not bold), e.g., second element of $\mathbf{x}$ is ${x}_2$
- Representing a point in space: $[x_1,  \space x_2] = [12, \space 4]$
    - Vector of length: two, represents location in 2D matrix
    - Vector of length: three, represents location in 3D cube
    - Vector of n length, represents location in n-dimensional tensor

In [ ]:
import numpy as np

x_vector = np.array([1,2,3]) #column
print(x_vector)
print(type(x_vector), len(x_vector), x_vector.shape)

[1 2 3]
<class 'numpy.ndarray'> 3 (3,)


`.shape` is an attribute to check for `np.array()` shape (or dimension)
and we could indexed it by using: e.g., `x_vector[0]` (as python start its index at 0), this will return 1 (int). 

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## 1.2.1 Vector Transpoition
- Example: 

$$[x_{1}, \space x_{2}, \space x_{3}]\top =
\begin{bmatrix}
x_{1} \\\\
x_{2} \\\\
x_{3}
\end{bmatrix}
$$

- Tranpsotion is denoted as $-\top$
- Transpose row vector $\to$ column vector, or column vector $\to$ row vector. (shape $(3,1)$ $\to$ shape $(1,3)$)


In [7]:
import numpy as np

print(x_vector.T, x_vector.T.shape)

y_vector = np.array([1,2,3,4]) #column
print(y_vector.shape, y_vector.T, y_vector.T.shape)

z_vector = np.array([[1,2,3], [4,5,6], [7,8,9]]) #rows and columns
print(z_vector.T)

[1 2 3] (3,)
(4,) [1 2 3 4] (4,)
[[1 4 7]
 [2 5 8]
 [3 6 9]]


`np.array()` for higher dimensions, it will needs more `[]`. so it defines both row, column.

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## 1.2.2 Zero Vectors
- Have no effects if added to another vectors

In [8]:
import numpy as np

print(np.zeros(3))

[0. 0. 0.]


Zero Vector can be defined using: `np.zeros(<value>)`

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## 1.2.3 Vectors in PyTorch

In [9]:
import torch

x_vector = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x_vector.shape, len(x_vector))

torch.Size([3, 3]) 3


Torch use `torch.tensor()` to define array, similarly to NumPy.

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## 1.3 Norms
- Vector represent a magnitude (ขนาด) and direction from origin

- **Norm are function that quantify vector magnitude** (ฟังก์ชันที่ใช้วัดขนาดของเวกเตอร์)

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## 1.3.1 $L^{2}$ Norm (Euclidean Norm)
- Described by:

$$
\begin{equation}
\|x\|_2 = \sqrt{\sum_{i=1}^{n} x_i^2}
\end{equation}
$$

(**How it works**: square root of sum of all element that squared by 2)
- Measures simple (Euclidean) distance from origin
- Most common norm in Machine Learning
    - Insteaad of $\|x\|_2$, it can be denoted as $\|x\|$

In [17]:
import numpy as np

x_l2 = np.array([1,2,3])
print(((1**2) + (2**2) + (3**2))**(1/2))

#iterates through each element to computes euclidean norm.
summ = 0
for _ in range(len(x_l2)):
    summ += (x_l2[_]**2)

print(f'Iterates: {summ**(1/2)}')

#or use np.linalg.norm()
from numpy import linalg as LA
print(f'LA: {LA.norm(x_l2)}')
print(f'np.linalg.norm: {np.linalg.norm(x_l2)}') #this function will default to euclidean norm.

3.7416573867739413
Iterates: 3.7416573867739413
LA: 3.7416573867739413
np.linalg.norm: 3.7416573867739413


So this mean, vector `x_l2` has a length of $25.6$ meters.

As you can see: we could use many different ways to compute $L^2$ Norm:
- `np.linalg.norm()`  This is the easist way as this function default to $L^2$ Norm.
- Or simply use `from numpy import linalg as LA` (LA is common alias) and then `LA.norm()`.
- Or if you understand it just iterates through each element or if you know what element is inside just square each element by 2 and then sum it and square root.

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## 1.3.2 Unit Vector
- Special case of vector where its length is equal to $1$.
    - if $\|x\| = 1$, $x$ is unit vector.
- Technically, $x$ is a unit vector with "unit norm", i.e., $\|x\| = 1$

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## 1.3.3 $L^1$ Norm
- Described by:

$$
\begin{equation}
\|x\|_1 = \sum_{i=1}^{n} |x_i|
\end{equation}
$$

- Another common norm in Machine Learning
- Varies linearly at all locations whether near or far from origin
- Used whenever difference between zero and non-zero is key.

In [19]:
import numpy as np

x_l1 = np.array([1,2,3])
print(np.abs(1) + np.abs(2) + np.abs(3)) #basic

#or iterate through each element.
summ = 0
for _ in range(len(x_l1)):
    summ += (np.abs(x_l1[_]))
    
print(f'Iterates: {summ}')

#or using np.linalg.norm(, ord=1)
from numpy import linalg as LA
print(f'LA: {LA.norm(x_l2, ord=1)}')
print(f'np.linalg.norm: {np.linalg.norm(x_l2, ord=1)}')

6
Iterates: 6
LA: 6.0
np.linalg.norm: 6.0


So the $L^1$ norm result of this vector is $6$.

We can use `np.linalg.norm(, ord=1)` to specify which order of norm function will be use to compute. in this case it's $1$ for $L^1$ norm.

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## Squared $L^2$ Norm
- Basically sum of all element squared by $2$ (without square root because this is squared $L^2$ norm).
- Described by:

$$
\begin{equation}
\|x\|_2^2 = \sum_{i=1}^{n} x_i^2
\end{equation}
$$

- Computationally cheaper to compute than $L^2$ norm because:
    - Squared $L^2$ Norm equals simply $x\top{x}$ ($x$ tranposed multiplied with vector $x$)
    - Derivative (used to train many Machine Learning algorithms) of element $x$ , requires that element alone, whereas $L^2$ norm requires $x$ vector.
    อนุพันธ์ คำนวณจาก องค์ประกอบเดี่ยว $x$ เพียงตัวเดียวในขณะที่ ค่า $L^2$ Norm จำเป็นต้องใช้ เวกเตอร์ $x$ ทั้งชุด
- Downside is it grows slowly near origin, so can't be used if distinguishing between zero and near-zero is important.

ข้อเสียคือ ค่าจะเพิ่มขึ้นช้ามากใกล้จุดกำเนิด (origin) ดังนั้น ไม่เหมาะสำหรับกรณีที่ต้องแยกความแตกต่างระหว่างค่าเป็นศูนย์กับค่าใกล้ศูนย์อย่างชัดเจน

In [2]:
import numpy as np

x_sl2 = np.array([1,2,3])
print(f'Basic: {1**2 + 2**2 + 3**2}')

#iteration
summ = 0
for _ in range(len(x_sl2)):
    summ += (x_sl2[_]**2)
    
print(f'Iterates: {summ}')

#using LA or linalg.norm()
from numpy import linalg as LA
print(f'LA: {(LA.norm(x_sl2))**2}')
print(f'np.linalg.norm: {(np.linalg.norm(x_sl2))**2}')

Basic: 14
Iterates: 14
LA: 14.0
np.linalg.norm: 14.0


It's just $L^2$ norm with no square root, but with `np.linalg.norm(x)` we just need to square it up.
Or we can just use `np.dot()` to calculate this Squared $L^2$ Norm.

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## Max Norm ($L^{\infty}$ Norm/Supremum Norm)
- Described by:

$$
\begin{equation}
\|x\|_{\infty} = \max_{i=1,\dots,n} |x_i|
\end{equation}
$$

- Also appear frequently in Machine Learning
- Returns the absolute value of the largest-magnitude element.

In [1]:
import numpy as np

x_max = np.array([1,2,3])
print(f'Basic: {np.max([np.abs(1), np.abs(2), np.abs(3)])}')

Basic: 3


It's basically maximum value of absoluted element in a vector.

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## Generalized $L^{p}$ Norm
- Described by:

$$
\begin{equation}
\|x\|_p = \left( \sum_{i=1}^{n} |x_i|^p \right)^{\frac{1}{p}}, \quad p \ge 1
\end{equation}
$$

- If we want to calculate $L^2$ Norm, we can just enter `p = 2`:
    - $p$ must be real number.
    - Greater than or equal to $1$
- Can derive $L^1$, $L^2$, and $L^{\infty}$ norm formulae by substituting (แทนที่) $p$.

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## Basis Vectors
- Can be scaled to represent any vector in a given vector space
- Typically use unit vector along axes of vector space

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## Orthogonal Vectors
- $x$ and $y$ are orthogonal vector if $x\top y = 0$
- Are at $\deg{90}$ angle to each other (assuming non-zero norms)
- n-dimensional space has max $n$ mutually orthogonal vector
    - Example: if it's 3 dimensional space then mostly it has maximum 3 mutually orthogonal vectors.
- **Orthogonal** vectors are orthogonal and all have unit norm
    - Basis vectors are an example.

In [2]:
import numpy as np

i_ortho = np.array([1,0])
j_ortho = np.array([0,1])
print(np.dot(i_ortho,j_ortho))

0


After `np.dot(i_ortho, j_ortho)`, it clearly showing that the result of dot product is 0, which relate to that $x$, $y$ are orthogonal if $x\top y = 0$

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

## Matrics
- 2-dimensional array of numbers
- Denoted in uppercase, italics, bold
- height given priority ahead of width in notation, i.e., $(\text{n}_\text{rows}, \text{n}_\text{column})$
    - If $\mathbf{x}$ has 3 rows and 2 columns, it's shape/dimension is $(3,2)$
- Individual scalar elements denoted in uppercase, italics only
    - Element in top-right corner of matrix $\mathbf{x}$ above would be $\mathbf{x}_\text{1,2}$
- Colon represents an entire row or column:
    - Left column of matrix $\mathbf{x}$ is $\mathbf{x}_\text{:,1}$
    - Middle row of matrix $\mathbf{x}$ is $\mathbf{x}_\text{2,:}$

An example of matrix:

$$
\begin{bmatrix}
1 & 2 & 3 \\\\
4 & 5 & 6 \\\\
7 & 8 & 9
\end{bmatrix}
$$

In [ ]:
import numpy as np

x_matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x_matrix.shape, x_matrix.size)

#basic indexings
for _ in range(3):
    print(x_matrix[0][_])

(3, 3) 9
1
2
3


## Matrics in PyTorch

In [18]:
import torch

x_matrix = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x_matrix.shape, x_matrix.size)

torch.Size([3, 3]) <built-in method size of Tensor object at 0x7feec2c69a30>
